name: New Resource Request
description: Request addition of a new MOTBX resource
title: "[new-resource-request]: "
labels: ["new-resource-request"]
assignees:
  - tgttunstall
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing to EATRIS Multi-omics Toolbox resources!
  - type: textarea
    id: motivation
    attributes:
      label: New Resource Request
      description: Why should this resource be added?
      placeholder: Describe the reason for this request
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Information about the new resource
  - type: input
    id: title
    attributes:
      label: Resource Title
      description: Which title do you suggest for this resource?
      placeholder: Title
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: Resource URL
      description: Please share a long-lasting link to the resource
      placeholder: A URL, preferably a persistent identifier, e.g., a DOI
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Resource Description
      description: Please provide a few sentences describing the resource
      placeholder: Description
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Resource Category and Subcategory
      description: Can you suggest a MOTBX category and subcategory for this resource?
      multiple: false
      options:
        - Genomics - Guidelines and best practices
        - Genomics - Laboratory protocols and methods
        - Genomics - Translational research use case
        - Epigenomics - Guidelines and best practices
        - Epigenomics - Laboratory protocols and methods
        - Epigenomics - Translational research use case
        - Transcriptomics - Guidelines and best practices
        - Transcriptomics - Laboratory protocols and methods
        - Transcriptomics - Translational research use case
        - Proteomics - Guidelines and best practices
        - Proteomics - Laboratory protocols and methods
        - Proteomics - Translational research use case
        - Metabolomics - Guidelines and best practices
        - Metabolomics - Laboratory protocols and methods
        - Metabolomics - Translational research use case
        - Quality Control and Assessment - Guidelines and best practices
        - Quality Control and Assessment - Reference materials for quality control
        - Quality Control and Assessment - Proficiency testing and external quality assessment
        - Quality Control and Assessment - Quality certification
        - Data Management and Stewardship - Guidelines and best practices
        - Data Management and Stewardship - Data and metadata standards
        - Data Management and Stewardship - Databases and catalogues
        - Data Management and Stewardship - Translational research use cases
        - Data Analysis - Guidelines and best practices
        - Data Analysis - Computing platforms
        - Data Analysis - Software applications and workflows
        - Data Analysis - Translational research use cases
    validations:
      required: false
  - type: dropdown
    id: existingtags
    attributes:
      label: Resource Tags (select from exisiting one)
      description: Can you suggest tags for this resource?
      multiple: true
      options:
        - guideline
        - protocol
    validations:
      required: true
  - type: input
    id: newtags
    attributes:
      label: New resource Tags
      description: Would you like to suggest new tags for this resource?
      placeholder: New tag(s)
    validations:
      required: false
