name: Resource Update Request
description: Request an update of an exisiting MOTBX resource
title: "[resource-update-request]: "
labels: ["resource-update-request"]
assignees:
  - emanuelaoldoni
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing to EATRIS Multi-omics Toolbox resources!
  - type: input
    id: resource
    attributes:
      label: Indicate Resource
      description: Which resource should be updated?
      placeholder: Please refer to file, resource name, or URL
    validations:
      required: true
  - type: dropdown
    id: element
    attributes:
      label: Element(s) to Update
      multiple: true
      description: Which information should be updated?
      options:
        - Resource title
        - Resource description
        - Resource URL
        - Resource category and/or subcategory
        - Resource tags
      default: 0
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Update Request
      description: Why should this resource be updated?
      placeholder: Describe the reason for this request, e.g., 'outdated URL'
    validations:
      required: true
  - type: textarea
    id: request
    attributes:
      label: Update Information
      description: Please suggest updated information describing the resource
      placeholder: e.g., updated URL
    validations:
      required: true
