name: Other Issue
description: Report a bug, request a feature, or provide feedback
title: "[other-issue]: "
labels: ["other-issue"]
assignees:
  - niehues
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing to this repository!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: e.g., email@example.com
    validations:
      required: false
  - type: textarea
    id: issue
    attributes:
      label: Report issue
      description: What would you like to report?
      placeholder: Describe the issue
    validations:
      required: true
  - type: dropdown
    id: issuetype
    attributes:
      label: Type of issue
      multiple: true
      description: Can you select a category for this issue?
      options:
        - Report a bug
        - Request change to MOTBX resource schema
        - Request additional functionality
      default: 0
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## EATRIS Privacy Policy
  - type: checkboxes
    id: privacy
    attributes:
      label: Privacy Policy
      description: By submitting this issue, you agree to [EATRIS Privacy Policy](https://eatris.eu/wp-content/uploads/2020/03/EATRIS_Privacy-Policy-website_updated-20200511.pdf)
      options:
        - label: I agree to EATRIS Privacy Policy
          required: true