name: Resource Update Request
description: Request an update of an exisiting MOTBX resource
title: "[resource-update-request]: "
labels: ["resource-update-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing to EATRIS Multi-omics Toolbox resources!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: e.g., email@example.com
    validations:
      required: false
  - type: input
    id: resource
    attributes:
      label: Indicate Resource
      description: Which resource should be updated?
      placeholder: Please refer to file, resource name, or URL
    validations:
      required: true
- type: dropdown
    id: element
    attributes:
      label: Element(s) to Update
      multiple: true
      description: Which information should be updated?
      options:
        - Resource title
        - Resource description
        - Resource URL
        - Resource category or subcategory
        - Resource tags
      default: 0
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Update Request
      description: Why should this resource be updated?
      placeholder: Describe the reason for this request, e.g., outdated URL
    validations:
      required: true
  - type: textarea
    id: request
    attributes:
      label: Update Information
      description: Please suggest updated information describing the resource
      placeholder: e.g., updated URL
    validations:
      required: true
  - type: checkboxes
    id: privacy
    attributes:
      label: Privacy Policy
      description: By submitting this issue, you agree to [EATRIS Privacy Policy](https://eatris.eu/wp-content/uploads/2020/03/EATRIS_Privacy-Policy-website_updated-20200511.pdf)
      options:
        - label: I agree to EATRIS Privacy Policy
          required: true