name: motbxtools
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - ipykernel=6.19.2
  - ipython=8.12.0
  - jsonschema=4.17.3
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - python=3.11.4
  - pyyaml=6.0
  - requests=2.27.1
