name: create_summary

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of resources summary'
        required: false
        default: 'latest'

permissions:
  contents: write
  pull-requests: write

jobs:
  create_summary:
    runs-on: ubuntu-latest

    defaults:
        run:
          shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniforge-variant: Mambaforge
          channels: conda-forge
          python-version: '3.11'
          activate-environment: motbxtools_min
          environment-file: envs/motbxtools_min.yml
          use-mamba: true

      - name: Build environment and install local motbxtools Python library
        run: |
          conda activate motbxtools_min
          python -m pip install -e .

      - name: Execute Python script to create resources summary
        run: |
          python src/motbxtools/utils/summarise_resources.py ${{github.event.inputs.version}}

      - name: Commit changes and create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "[create-pull-request] automated resource summary test"
          branch: create-pull-request/resource_summary
          add-paths: |
            resources/summary/*
