name: create_summary

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
        run:
          shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniforge-variant: Mambaforge
          channels: conda-forge
          python-version: '3.11'
          activate-environment: motbxtools_min
          environment-file: envs/motbxtools_min.yml
          use-mamba: true

      - name: Build environment and install local motbxtools Python library
        run: |
          conda activate motbxtools_min
          python -m pip install -e .

      - name: Execute Python script to create resources summary
        run: |
          python src/motbxtools/utils/summarise_resources.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated files" --allow-empty)

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
