name: validate_resources

on:
  pull_request:
    branches:
      - main
    paths:
      - resources/*.yaml

jobs:
  validate_resources:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniforge-variant: Mambaforge
          channels: conda-forge
          python-version: '3.11'
          activate-environment: motbxtools_min
          environment-file: envs/motbxtools_min.yml
          use-mamba: true

      - name: Activate conda environment and install local motbxtools Python library
        run: |
          conda activate motbxtools_min
          python -m pip install -e .

      - name: Get changed resource files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
            files_yaml: |
              resources:
                - curated/**

      - name: Execute Python script to create resources summary
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            python src/motbxtools/utils/validate_resource.py "$file was changed"
          done
